# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfigName.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(548, 206)
        Dialog.setMinimumSize(QtCore.QSize(548, 206))
        Dialog.setMaximumSize(QtCore.QSize(548, 206))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 181, 31))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 80, 501, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.Button_Ok = QtWidgets.QPushButton(Dialog)
        self.Button_Ok.setGeometry(QtCore.QRect(390, 150, 131, 40))
        self.Button_Ok.setObjectName("Button_Ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置文件名"))
        self.label.setText(_translate("Dialog", "输入配置文件名："))
        self.Button_Ok.setText(_translate("Dialog", "确定"))
